import { defineConfig } from "oxlint";

const nextjsSpecialFiles = [
  ".storybook/main.ts",
  ".storybook/preview.tsx",
  "next.config.ts",
  "oxlint.config.ts",
  "postcss.config.mjs",
  "src/**/default.tsx",
  "src/**/error.tsx",
  "src/**/forbidden.tsx",
  "src/**/global-error.tsx",
  "src/**/instrumentation-client.ts",
  "src/**/instrumentation.ts",
  "src/**/layout.tsx",
  "src/**/loading.tsx",
  "src/**/not-found.tsx",
  "src/**/page.tsx",
  "src/**/proxy.ts",
  "src/**/sitemap.ts",
  "src/**/template.tsx",
  "src/**/unauthorized.tsx",
  "vitest.config.ts",
  "vitest.globalSetup.ts",
];

export default defineConfig({
  plugins: [
    "import",
    "jsdoc",
    "jsx-a11y",
    "nextjs",
    "oxc",
    "promise",
    "react",
    "typescript",
    "unicorn",
    "vitest",
  ],
  env: {
    builtin: true,
    browser: true,
    node: true,
  },
  ignorePatterns: [
    ".next/**",
    "build/**",
    "next-env.d.ts",
    "node_modules/**",
    "out/**",
    "public/**",
    "src/api/openapi/**",
    "storybook-static/**",
  ],
  jsPlugins: [
    "./scripts/oxlint-plugin-entry-point.mjs",
    "./scripts/oxlint-plugin-fn-style.mjs",
    "./scripts/oxlint-plugin-sort-hook-deps.mjs",
    "@tanstack/eslint-plugin-query",
    { name: "import-js", specifier: "eslint-plugin-import" },
    { name: "react-hooks-js", specifier: "eslint-plugin-react-hooks" },
  ],
  rules: {
    // ── OxC rules ──
    "oxc/approx-constant": "error",
    "oxc/bad-bitwise-operator": "error",
    "oxc/branches-sharing-code": "error",
    "oxc/misrefactored-assign-op": "error",
    "oxc/no-accumulating-spread": "error",
    "oxc/no-barrel-file": ["error", { threshold: 1 }],
    "oxc/no-const-enum": "error",
    "oxc/no-map-spread": "error",
    "oxc/no-this-in-exported-function": "error",

    // ── ESLint core ──
    "array-callback-return": "error",
    curly: "error",
    "default-case": "warn",
    "default-case-last": "warn",
    "default-param-last": "warn",
    eqeqeq: "error",
    "grouped-accessor-pairs": "warn",
    "guard-for-in": "warn",
    "no-console": ["warn", { allow: ["error", "warn"] }],
    "no-else-return": "warn",
    "no-empty": "warn",
    "no-empty-function": "warn",
    "no-eq-null": "error",
    "no-implicit-coercion": "warn",
    "no-lonely-if": "warn",
    "no-multi-str": "error",
    "no-negated-condition": "warn",
    "no-nested-ternary": "warn",
    "no-param-reassign": "warn",
    "no-proto": "warn",
    "no-restricted-globals": "warn",
    "no-throw-literal": "warn",
    "no-useless-catch": "warn",
    "no-useless-concat": "warn",
    "no-var": "warn",
    "no-void": ["warn", { allowAsStatement: true }],
    "operator-assignment": "warn",
    "prefer-object-spread": "warn",
    "prefer-template": "warn",
    "sort-imports": ["warn", { ignoreDeclarationSort: true }],
    "symbol-description": "warn",
    yoda: "warn",

    // ── TypeScript ──
    "@typescript-eslint/array-type": "warn",
    "@typescript-eslint/ban-ts-comment": "off",
    "@typescript-eslint/consistent-type-definitions": "warn",
    "@typescript-eslint/consistent-type-imports": [
      "warn",
      { prefer: "type-imports", fixStyle: "separate-type-imports" },
    ],
    "@typescript-eslint/no-dynamic-delete": "warn",
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/no-inferrable-types": "warn",
    "@typescript-eslint/no-namespace": "warn",
    "@typescript-eslint/no-require-imports": "off",
    "@typescript-eslint/no-unnecessary-template-expression": "off",
    "@typescript-eslint/no-unused-vars": "off",
    "@typescript-eslint/only-throw-error": "off",
    "@typescript-eslint/prefer-as-const": "warn",
    "@typescript-eslint/prefer-enum-initializers": "warn",
    "@typescript-eslint/prefer-for-of": "warn",

    // ── TypeScript (type-aware) ──
    // Replaced from non-type-aware versions
    "typescript/require-await": "warn",
    "typescript/only-throw-error": "warn",
    "typescript/no-unnecessary-template-expression": "warn",
    // Error level (safety-critical)
    "typescript/no-floating-promises": "error",
    "typescript/no-misused-promises": "error",
    "typescript/await-thenable": "error",
    "typescript/no-for-in-array": "error",
    // Warn level (code quality)
    "typescript/no-unnecessary-type-assertion": "warn",
    "typescript/no-unnecessary-type-arguments": "warn",
    "typescript/no-unnecessary-boolean-literal-compare": "warn",
    "typescript/restrict-plus-operands": "warn",
    "typescript/restrict-template-expressions": "warn",
    "typescript/prefer-optional-chain": "warn",
    "typescript/prefer-nullish-coalescing": "warn",
    "typescript/return-await": "warn",
    "typescript/switch-exhaustiveness-check": "warn",

    // ── React ──
    "react/jsx-boolean-value": "warn",
    "react/jsx-curly-brace-presence": "warn",
    "react/jsx-fragments": "warn",
    "react/jsx-no-target-blank": "off",
    "react/jsx-props-no-spread-multi": "warn",
    "react/no-unknown-property": "off",
    "react/no-unsafe": "off",
    "react/react-in-jsx-scope": "off",
    "react/self-closing-comp": "warn",

    // ── Import ──
    "import/consistent-type-specifier-style": "error",
    "import/default": "error",
    "import/export": "error",
    "import/first": "error",
    "import/named": "error",
    "import/namespace": "error",
    "import/no-anonymous-default-export": "error",
    "import/no-commonjs": "error",
    "import/no-cycle": "error",
    "import/no-default-export": "error",
    "import/no-duplicates": "error",
    "import/no-dynamic-require": "error",
    "import/no-empty-named-blocks": "error",
    "import/no-mutable-exports": "error",
    "import/no-named-as-default": "error",
    "import/no-named-as-default-member": "error",
    "import/no-named-default": "error",
    "import/no-namespace": "error",
    "import/no-self-import": "error",
    "import/no-webpack-loader-syntax": "error",

    // ── Unicorn ──
    "unicorn/error-message": "warn",
    "unicorn/explicit-length-check": "warn",
    "unicorn/filename-case": [
      "warn",
      { cases: { camelCase: true, pascalCase: true } },
    ],
    "unicorn/new-for-builtins": "warn",
    "unicorn/numeric-separators-style": "warn",
    "unicorn/prefer-array-find": "warn",
    "unicorn/prefer-at": "warn",
    "unicorn/prefer-number-properties": "warn",
    "unicorn/prefer-string-slice": "warn",
    "unicorn/prefer-string-trim-start-end": "warn",
    "unicorn/require-number-to-fixed-digits-argument": "warn",

    // ── jsx-a11y ──
    "jsx-a11y/no-static-element-interactions": "warn",
    "jsx-a11y/alt-text": ["warn", { elements: ["img"], img: ["Image"] }],

    // ── Next.js ──
    "nextjs/google-font-display": "error",
    "nextjs/google-font-preconnect": "error",
    "nextjs/inline-script-id": "error",
    "nextjs/next-script-for-ga": "error",
    "nextjs/no-assign-module-variable": "error",
    "nextjs/no-async-client-component": "error",
    "nextjs/no-before-interactive-script-outside-document": "error",
    "nextjs/no-css-tags": "error",
    "nextjs/no-document-import-in-page": "error",
    "nextjs/no-duplicate-head": "error",
    "nextjs/no-head-element": "error",
    "nextjs/no-head-import-in-document": "error",
    "nextjs/no-html-link-for-pages": "error",
    "nextjs/no-img-element": "error",
    "nextjs/no-page-custom-font": "error",
    "nextjs/no-script-component-in-head": "error",
    "nextjs/no-styled-jsx-in-document": "error",
    "nextjs/no-sync-scripts": "error",
    "nextjs/no-title-in-document-head": "error",
    "nextjs/no-typos": "error",
    "nextjs/no-unwanted-polyfillio": "error",

    // ── eslint-plugin-import (jsPlugin) ──
    "import-js/newline-after-import": "error",

    // ── @tanstack/eslint-plugin-query (jsPlugin) ──
    "@tanstack/query/exhaustive-deps": "error",
    "@tanstack/query/infinite-query-property-order": "error",
    "@tanstack/query/mutation-property-order": "error",
    "@tanstack/query/no-rest-destructuring": "warn",
    "@tanstack/query/no-unstable-deps": "error",
    "@tanstack/query/no-void-query-fn": "error",
    "@tanstack/query/stable-query-client": "error",

    // ── eslint-plugin-react-hooks (jsPlugin) ──
    "react-hooks-js/exhaustive-deps": "error",
    "react-hooks-js/rules-of-hooks": "error",
    "react-hooks-js/component-hook-factories": "error",
    "react-hooks-js/config": "error",
    "react-hooks-js/error-boundaries": "error",
    "react-hooks-js/gating": "error",
    "react-hooks-js/globals": "error",
    "react-hooks-js/immutability": "error",
    "react-hooks-js/incompatible-library": "error",
    "react-hooks-js/preserve-manual-memoization": "error",
    "react-hooks-js/purity": "error",
    "react-hooks-js/refs": "error",
    "react-hooks-js/set-state-in-effect": "error",
    "react-hooks-js/set-state-in-render": "error",
    "react-hooks-js/static-components": "error",
    "react-hooks-js/unsupported-syntax": "error",
    "react-hooks-js/use-memo": "error",

    // ── fn-style (jsPlugin) ──
    "fn-style/no-top-level-arrow": "error",

    // ── entry-point (jsPlugin) ──
    "entry-point/no-index-tsx": "error",

    // ── sort-hook-deps (jsPlugin) ──
    "sort-hook-deps/sort-deps": "error",
  },
  overrides: [
    {
      // Next.js special files + config files → allow default export, relax filename
      files: nextjsSpecialFiles,
      rules: {
        "import/no-default-export": "off",
        "unicorn/filename-case": "off",
      },
    },
    {
      // Storybook stories
      files: ["**/*.stories.*", "**/*.story.*"],
      rules: {
        "import/no-anonymous-default-export": "off",
        "import/no-default-export": "off",
        "react-hooks-js/rules-of-hooks": "off",
        "storybook/await-interactions": "error",
        "storybook/context-in-play-function": "error",
        "storybook/default-exports": "error",
        "storybook/hierarchy-separator": "warn",
        "storybook/meta-inline-properties": "warn",
        "storybook/meta-satisfies-type": "error",
        "storybook/no-redundant-story-name": "warn",
        "storybook/no-renderer-packages": "error",
        "storybook/no-stories-of": "error",
        "storybook/prefer-pascal-case": "warn",
        "storybook/story-exports": "error",
        "storybook/use-storybook-expect": "error",
        "storybook/use-storybook-testing-library": "error",
      },
      jsPlugins: ["eslint-plugin-storybook"],
    },
    {
      // Storybook main config
      files: [".storybook/main.*"],
      rules: {
        "storybook/no-uninstalled-addons": "error",
      },
      jsPlugins: ["eslint-plugin-storybook"],
    },
    {
      // Test files
      files: ["**/*.test.*", "**/*.spec.*"],
      rules: {
        "no-empty-function": "off",
        "typescript/unbound-method": "off",
        "vitest/consistent-each-for": "error",
        "vitest/consistent-test-filename": "error",
        "vitest/consistent-test-it": ["error", { fn: "it" }],
        "vitest/consistent-vitest-vi": "error",
        "vitest/expect-expect": "error",
        "vitest/hoisted-apis-on-top": "error",
        "vitest/no-alias-methods": "error",
        "vitest/no-conditional-expect": "error",
        "vitest/no-conditional-in-test": "error",
        "vitest/no-conditional-tests": "error",
        "vitest/no-disabled-tests": "warn",
        "vitest/no-done-callback": "error",
        "vitest/no-duplicate-hooks": "error",
        "vitest/no-focused-tests": "error",
        "vitest/no-identical-title": "error",
        "vitest/no-mocks-import": "error",
        "vitest/no-standalone-expect": "error",
        "vitest/no-test-prefixes": "error",
        "vitest/no-test-return-statement": "error",
        "vitest/no-unneeded-async-expect-function": "error",
        "vitest/prefer-called-once": "error",
        "vitest/prefer-called-with": "error",
        "vitest/prefer-comparison-matcher": "error",
        "vitest/prefer-describe-function-title": "error",
        "vitest/prefer-each": "error",
        "vitest/prefer-equality-matcher": "error",
        "vitest/prefer-expect-resolves": "error",
        "vitest/prefer-expect-type-of": "error",
        "vitest/prefer-hooks-on-top": "error",
        "vitest/prefer-mock-promise-shorthand": "error",
        "vitest/prefer-spy-on": "error",
        "vitest/prefer-strict-equal": "error",
        "vitest/prefer-to-be": "error",
        "vitest/prefer-to-be-object": "error",
        "vitest/prefer-to-contain": "error",
        "vitest/prefer-to-have-length": "error",
        "vitest/require-hook": "error",
        "vitest/require-local-test-context-for-concurrent-snapshots": "error",
        "vitest/require-to-throw-message": "error",
        "vitest/require-top-level-describe": "error",
        "vitest/valid-describe-callback": "error",
        "vitest/valid-expect": "error",
      },
    },
    {
      // Scripts
      files: ["scripts/**"],
      rules: {
        "@typescript-eslint/no-redundant-type-constituents": "off",
        "import/no-anonymous-default-export": "off",
        "import/no-default-export": "off",
        "unicorn/filename-case": "off",
      },
    },
  ],
});
