import { defineConfig } from "oxlint";

export default defineConfig({
  options: {
    reportUnusedDisableDirectives: "error",
    respectEslintDisableDirectives: false,
    typeAware: true,
    typeCheck: true,
  },
  env: {
    browser: true,
    builtin: true,
    node: true,
  },
  plugins: [
    "eslint",
    "import",
    "jsdoc",
    "jsx-a11y",
    "nextjs",
    "node",
    "oxc",
    "promise",
    "react",
    "typescript",
    "unicorn",
    "vitest",
  ],
  jsPlugins: [
    "./tools/oxlint-rules/index.ts",
    "@tanstack/eslint-plugin-query",
    { name: "react-doctor", specifier: "oxlint-plugin-react-doctor" },
  ],
  settings: {
    vitest: { typecheck: true },
    "react-doctor": { capabilities: ["react-compiler"] },
  },
  ignorePatterns: ["public/**", "src/api/openapi/**", "src/mocks/**"],
  categories: {
    correctness: "error",
    nursery: "error",
    pedantic: "error",
    perf: "error",
    restriction: "error",
    style: "error",
    suspicious: "error",
  },
  rules: {
    // ── eslint built-in rules ──
    "eslint/arrow-body-style": "off",
    "eslint/capitalized-comments": "off",
    "eslint/func-style": "off",
    "eslint/id-length": "off",
    "eslint/max-lines": "off",
    "eslint/max-lines-per-function": "off",
    "eslint/max-params": "off",
    "eslint/max-statements": "off",
    "eslint/no-console": ["error", { allow: ["error", "warn"] }],
    "eslint/no-duplicate-imports": [
      "error",
      { allowSeparateTypeImports: true },
    ],
    "eslint/no-magic-numbers": "off",
    "eslint/no-ternary": "off",
    "eslint/no-undefined": "off",
    "eslint/no-underscore-dangle": "off",
    "eslint/no-void": ["error", { allowAsStatement: true }],
    "eslint/one-var": "off",
    "eslint/prefer-named-capture-group": "off",
    "eslint/require-await": "off",
    "eslint/sort-imports": ["error", { ignoreDeclarationSort: true }],
    "eslint/sort-keys": "off",

    // ── eslint-plugin-import (built-in) ──
    "import/exports-last": "off",
    "import/group-exports": "off",
    "import/max-dependencies": "off",
    "import/no-named-export": "off",
    "import/no-relative-parent-imports": "off",
    "import/no-unassigned-import": "off",
    "import/prefer-default-export": "off",
    "import/unambiguous": "off",

    // ── eslint-plugin-jsdoc (built-in) ──
    "jsdoc/require-param": "off",
    "jsdoc/require-param-description": "off",
    "jsdoc/require-param-type": "off",
    "jsdoc/require-returns": "off",
    "jsdoc/require-returns-description": "off",
    "jsdoc/require-returns-type": "off",

    // ── eslint-plugin-node (built-in) ──
    "node/no-process-env": "off",

    // ── oxlint built-in rules ──
    "oxc/no-async-await": "off",
    "oxc/no-optional-chaining": "off",
    "oxc/no-rest-spread-properties": "off",

    // ── eslint-plugin-promise (built-in) ──
    "promise/avoid-new": "off",
    "promise/prefer-await-to-callbacks": "off",

    // ── eslint-plugin-react (built-in) ──
    "react/forbid-component-props": "off",
    "react/jsx-filename-extension": ["error", { extensions: [".tsx"] }],
    "react/jsx-max-depth": "off",
    "react/jsx-no-literals": "off",
    "react/jsx-props-no-spreading": "off",
    "react/only-export-components": "off",
    "react/react-in-jsx-scope": "off",
    "react/no-unstable-nested-components": [
      "error",
      { propNamePattern: "{render,*Render}*" },
    ],

    // ── eslint-plugin-typescript (built-in) ──
    "typescript/array-type": [
      "error",
      { default: "array-simple", readonly: "array-simple" },
    ],
    "typescript/explicit-function-return-type": "off",
    "typescript/explicit-module-boundary-types": "off",
    "typescript/prefer-readonly-parameter-types": "off",
    "typescript/strict-void-return": "off",

    // ── eslint-plugin-unicorn (built-in) ──
    "unicorn/filename-case": [
      "error",
      { cases: { camelCase: true, kebabCase: true, pascalCase: true } },
    ],
    "unicorn/import-style": ["error", { styles: { zod: { named: true } } }],
    "unicorn/no-null": "off",
    "unicorn/no-useless-undefined": "off",
    "unicorn/prefer-global-this": "off",
    "unicorn/switch-case-braces": ["error", "avoid"],

    // ── eslint-plugin-vitest (built-in) ──
    "vitest/consistent-test-it": ["error", { fn: "it" }],
    "vitest/no-hooks": "off",
    "vitest/no-importing-vitest-globals": "off",
    "vitest/no-standalone-expect": [
      "error",
      { additionalTestBlockFunctions: ["it.for"] },
    ],
    "vitest/prefer-called-once": "off",
    "vitest/prefer-expect-assertions": "off",
    "vitest/prefer-importing-vitest-globals": "off",
    "vitest/prefer-lowercase-title": "off",
    "vitest/prefer-to-be-falsy": "off",
    "vitest/prefer-to-be-truthy": "off",
    "vitest/require-hook": "off",
    "vitest/require-mock-type-parameters": "off",
    "vitest/require-test-timeout": "off",

    // ── @tanstack/eslint-plugin-query (jsPlugin) ──
    "@tanstack/query/exhaustive-deps": "error",
    "@tanstack/query/infinite-query-property-order": "error",
    "@tanstack/query/mutation-property-order": "error",
    "@tanstack/query/no-rest-destructuring": "error",
    "@tanstack/query/no-unstable-deps": "error",
    "@tanstack/query/no-void-query-fn": "error",
    "@tanstack/query/prefer-query-options": "error",
    "@tanstack/query/stable-query-client": "error",

    // ── custom rules (jsPlugin: ./tools/oxlint-rules/) ──
    "custom-rules/no-index-tsx": "error",
    "custom-rules/no-restricted-syntax": [
      "error",
      {
        selector:
          "Program > VariableDeclaration > VariableDeclarator[init.type='ArrowFunctionExpression']",
        message: "Use function declarations at the top level",
      },
      {
        selector:
          "Program > ExportNamedDeclaration > VariableDeclaration > VariableDeclarator[init.type='ArrowFunctionExpression']",
        message: "Use function declarations for exported functions",
      },
    ],
    "custom-rules/sort-hook-deps": "error",

    // ── oxlint-plugin-react-doctor (jsPlugin) ──
    // 以下は `pnpm generate-oxlint-rules` が生成する。手で編集しないこと。
    // react-doctor:start
    "react-doctor/activity-wraps-effect-heavy-subtree": "error",
    "react-doctor/advanced-event-handler-refs": "error",
    "react-doctor/anchor-target-exists": "error",
    "react-doctor/async-await-in-loop": "error",
    "react-doctor/async-defer-await": "error",
    "react-doctor/async-parallel": "error",
    "react-doctor/auth-token-in-web-storage": "error",
    "react-doctor/class-component-missing-component-will-unmount-teardown":
      "error",
    "react-doctor/client-localstorage-no-version": "error",
    "react-doctor/client-passive-event-listeners": "error",
    "react-doctor/debounce-no-cleanup": "error",
    "react-doctor/dialog-has-accessible-name": "error",
    "react-doctor/effect-listener-cleanup-mismatch": "error",
    "react-doctor/effect-listener-cleanup-reference-mismatch": "error",
    "react-doctor/effect-needs-cleanup": "error",
    "react-doctor/effect-observer-needs-disconnect": "error",
    "react-doctor/effect-raf-loop-needs-cancel": "error",
    "react-doctor/effect-remove-listener-inline-handler": "error",
    "react-doctor/hook-import-rename-loses-use-prefix": "error",
    "react-doctor/hooks-no-nan-in-deps": "error",
    "react-doctor/html-label-has-single-control": "error",
    "react-doctor/html-no-invalid-paragraph-child": "error",
    "react-doctor/html-no-invalid-table-nesting": "error",
    "react-doctor/html-no-nested-form": "error",
    "react-doctor/html-no-nested-interactive": "error",
    "react-doctor/js-async-reduce-without-awaited-acc": "error",
    "react-doctor/js-batch-dom-css": "error",
    "react-doctor/js-cache-property-access": "error",
    "react-doctor/js-cache-storage": "error",
    "react-doctor/js-combine-iterations": "error",
    "react-doctor/js-early-exit": "error",
    "react-doctor/js-flatmap-filter": "error",
    "react-doctor/js-hoist-intl": "error",
    "react-doctor/js-hoist-regexp": "error",
    "react-doctor/js-index-maps": "error",
    "react-doctor/js-length-check-first": "error",
    "react-doctor/js-min-max-loop": "error",
    "react-doctor/js-set-map-lookups": "error",
    "react-doctor/js-tosorted-immutable": "error",
    "react-doctor/jsx-numeric-and-leaked-render": "error",
    "react-doctor/nextjs-async-client-component": "error",
    "react-doctor/nextjs-async-dynamic-api-not-awaited": "error",
    "react-doctor/nextjs-error-boundary-missing-use-client": "error",
    "react-doctor/nextjs-global-error-missing-html-body": "error",
    "react-doctor/nextjs-image-missing-sizes": "error",
    "react-doctor/nextjs-inline-script-missing-id": "error",
    "react-doctor/nextjs-metadata-url-consistency": "error",
    "react-doctor/nextjs-missing-metadata": "error",
    "react-doctor/nextjs-no-a-element": "error",
    "react-doctor/nextjs-no-client-fetch-for-server-data": "error",
    "react-doctor/nextjs-no-client-side-redirect": "error",
    "react-doctor/nextjs-no-css-link": "error",
    "react-doctor/nextjs-no-default-export-in-route-handler": "error",
    "react-doctor/nextjs-no-edge-og-runtime": "error",
    "react-doctor/nextjs-no-font-link": "error",
    "react-doctor/nextjs-no-google-analytics-script": "error",
    "react-doctor/nextjs-no-head-import": "error",
    "react-doctor/nextjs-no-img-element": "error",
    "react-doctor/nextjs-no-native-script": "error",
    "react-doctor/nextjs-no-polyfill-script": "error",
    "react-doctor/nextjs-no-redirect-in-try-catch": "error",
    "react-doctor/nextjs-no-script-in-head": "error",
    "react-doctor/nextjs-no-side-effect-in-get-handler": "error",
    "react-doctor/nextjs-no-use-search-params-without-suspense": "error",
    "react-doctor/nextjs-no-vercel-og-import": "error",
    "react-doctor/no-adjust-state-on-prop-change": "error",
    "react-doctor/no-arithmetic-on-optional-chained-operand": "error",
    "react-doctor/no-array-find-result-member-access-without-guard": "error",
    "react-doctor/no-array-index-as-key": "error",
    "react-doctor/no-array-index-deref-without-bounds-or-empty-guard": "error",
    "react-doctor/no-assertive-status": "error",
    "react-doctor/no-async-effect-callback": "error",
    "react-doctor/no-async-event-handler-without-reentry-guard": "error",
    "react-doctor/no-autoplay-without-muted": "error",
    "react-doctor/no-barrel-import": "error",
    "react-doctor/no-blocked-paste": "error",
    "react-doctor/no-boolean-toggle-without-functional-update": "error",
    "react-doctor/no-broken-image-source": "error",
    "react-doctor/no-call-component-as-function": "error",
    "react-doctor/no-collapsed-literal-or-chain-as-value": "error",
    "react-doctor/no-conflicting-spring-options": "error",
    "react-doctor/no-controlled-input-value-without-state-update": "error",
    "react-doctor/no-create-context-in-render": "error",
    "react-doctor/no-create-object-url-in-render": "error",
    "react-doctor/no-create-object-url-without-revoke": "error",
    "react-doctor/no-create-ref-in-function-component": "error",
    "react-doctor/no-create-store-in-render": "error",
    "react-doctor/no-default-props": "error",
    "react-doctor/no-deprecated-keyboard-event-keycode-which": "error",
    "react-doctor/no-derived-state": "error",
    "react-doctor/no-derived-state-effect": "error",
    "react-doctor/no-derived-useState": "error",
    "react-doctor/no-direct-state-mutation": "error",
    "react-doctor/no-document-start-view-transition": "error",
    "react-doctor/no-document-write": "error",
    "react-doctor/no-dynamic-import-path": "error",
    "react-doctor/no-eager-new-in-use-state-initializer": "error",
    "react-doctor/no-effect-chain": "error",
    "react-doctor/no-effect-event-handler": "error",
    "react-doctor/no-effect-event-in-deps": "error",
    "react-doctor/no-effect-wrapper-discards-callback-cleanup-return": "error",
    "react-doctor/no-event-handler": "error",
    "react-doctor/no-event-trigger-state": "error",
    "react-doctor/no-fetch-in-effect": "error",
    "react-doctor/no-fetch-response-used-without-status-check": "error",
    "react-doctor/no-fill-map-element-as-key": "error",
    "react-doctor/no-floating-then-in-jsx-handler": "error",
    "react-doctor/no-flush-sync": "error",
    "react-doctor/no-focusable-content-in-aria-hidden": "error",
    "react-doctor/no-full-lodash-import": "error",
    "react-doctor/no-giant-component": "error",
    "react-doctor/no-global-css-variable-animation": "error",
    "react-doctor/no-high-complexity-react-function": "error",
    "react-doctor/no-hydration-branch-on-browser-global": "error",
    "react-doctor/no-img-lazy-with-high-fetchpriority": "error",
    "react-doctor/no-impure-call-at-module-scope": "error",
    "react-doctor/no-impure-state-updater": "error",
    "react-doctor/no-indeterminate-attribute": "error",
    "react-doctor/no-initialize-state": "error",
    "react-doctor/no-inline-hoc-on-component": "error",
    "react-doctor/no-invalid-progress-range": "error",
    "react-doctor/no-json-parse-stringify-clone": "error",
    "react-doctor/no-jsx-element-type": "error",
    "react-doctor/no-large-animated-blur": "error",
    "react-doctor/no-layout-property-animation": "error",
    "react-doctor/no-legacy-class-lifecycles": "error",
    "react-doctor/no-legacy-context-api": "error",
    "react-doctor/no-loading-flag-reset-outside-finally": "error",
    "react-doctor/no-locale-format-in-render": "error",
    "react-doctor/no-many-boolean-props": "error",
    "react-doctor/no-match-media-in-state-initializer": "error",
    "react-doctor/no-mirror-prop-effect": "error",
    "react-doctor/no-mixed-srcset-descriptors": "error",
    "react-doctor/no-moment": "error",
    "react-doctor/no-multi-component-file": "error",
    "react-doctor/no-multiple-main-landmarks": "error",
    "react-doctor/no-multiple-unlabeled-navigation-landmarks": "error",
    "react-doctor/no-mutable-in-deps": "error",
    "react-doctor/no-mutate-queried-dom-node-in-component": "error",
    "react-doctor/no-mutate-then-set-or-return-same-reference": "error",
    "react-doctor/no-mutating-array-method-on-prop-or-hook-result": "error",
    "react-doctor/no-mutating-reducer-state": "error",
    "react-doctor/no-nested-component-definition": "error",
    "react-doctor/no-non-literal-selector-query-without-try-catch": "error",
    "react-doctor/no-non-null-assertion-on-maybe-undefined-result": "error",
    "react-doctor/no-nondeterministic-id-value-in-render-body": "error",
    "react-doctor/no-nullish-coalescing-arithmetic-precedence": "error",
    "react-doctor/no-object-keys-values-entries-on-maybe-undefined": "error",
    "react-doctor/no-object-or-array-coerced-to-string-in-template-literal":
      "error",
    "react-doctor/no-pass-data-to-parent": "error",
    "react-doctor/no-pass-live-state-to-parent": "error",
    "react-doctor/no-path-prefix-containment": "error",
    "react-doctor/no-permanent-will-change": "error",
    "react-doctor/no-placeholder-only-field": "error",
    "react-doctor/no-polymorphic-children": "error",
    "react-doctor/no-predicate-function-reference-in-boolean-position": "error",
    "react-doctor/no-prevent-default": "error",
    "react-doctor/no-promise-then-side-effect-in-effect-without-catch": "error",
    "react-doctor/no-prop-callback-in-effect": "error",
    "react-doctor/no-prop-callback-in-render": "error",
    "react-doctor/no-random-key": "error",
    "react-doctor/no-react-dom-deprecated-apis": "error",
    "react-doctor/no-react19-deprecated-apis": "error",
    "react-doctor/no-ref-current-in-render": "error",
    "react-doctor/no-render-in-render": "error",
    "react-doctor/no-render-prop-children": "error",
    "react-doctor/no-reset-all-state-on-prop-change": "error",
    "react-doctor/no-responsive-hidden-accessible-name": "error",
    "react-doctor/no-scale-from-zero": "error",
    "react-doctor/no-secrets-in-client-code": "error",
    "react-doctor/no-self-updating-effect": "error",
    "react-doctor/no-set-state-after-await-in-effect": "error",
    "react-doctor/no-set-state-in-render": "error",
    "react-doctor/no-side-effect-in-state-updater-function": "error",
    "react-doctor/no-spread-accumulator-in-reduce": "error",
    "react-doctor/no-spread-props-over-defaults-clobbers-with-undefined":
      "error",
    "react-doctor/no-srcset-without-sizes": "error",
    "react-doctor/no-stale-timer-ref": "error",
    "react-doctor/no-string-false-on-boolean-attribute": "error",
    "react-doctor/no-sync-xhr": "error",
    "react-doctor/no-transition-all": "error",
    "react-doctor/no-uncontrolled-input": "error",
    "react-doctor/no-undeferred-third-party": "error",
    "react-doctor/no-unescaped-dynamic-string-in-regexp": "error",
    "react-doctor/no-unguarded-browser-global-at-module-scope": "error",
    "react-doctor/no-unguarded-browser-global-in-render-or-hook-init": "error",
    "react-doctor/no-unguarded-numeric-input-parse": "error",
    "react-doctor/no-unguarded-throwing-parse-call": "error",
    "react-doctor/no-uninformative-aria-label": "error",
    "react-doctor/no-unowned-async-error-clear": "error",
    "react-doctor/no-unsafe-json-parse": "error",
    "react-doctor/no-unthrottled-scroll-mutation": "error",
    "react-doctor/no-usememo-simple-expression": "error",
    "react-doctor/no-whole-object-default-losing-per-key-defaults": "error",
    "react-doctor/no-whole-object-dep-with-member-reads": "error",
    "react-doctor/pointer-capture-needs-cancel-handler": "error",
    "react-doctor/prefer-dynamic-import": "error",
    "react-doctor/prefer-explicit-variants": "error",
    "react-doctor/prefer-html-dialog": "error",
    "react-doctor/prefer-use-effect-event": "error",
    "react-doctor/prefer-use-sync-external-store": "error",
    "react-doctor/prefer-useReducer": "error",
    "react-doctor/query-destructure-result": "error",
    "react-doctor/query-floating-mutate-async": "error",
    "react-doctor/query-mutation-missing-invalidation": "error",
    "react-doctor/query-no-mutation-in-effect-as-read": "error",
    "react-doctor/query-no-query-in-effect": "error",
    "react-doctor/query-no-rest-destructuring": "error",
    "react-doctor/query-no-usequery-for-mutation": "error",
    "react-doctor/query-no-void-query-fn": "error",
    "react-doctor/query-stable-query-client": "error",
    "react-doctor/radio-input-missing-name": "error",
    "react-doctor/radix-dialog-content-requires-title": "error",
    "react-doctor/radix-tabs-trigger-requires-list": "error",
    "react-doctor/react-compiler-no-manual-memoization": "error",
    "react-doctor/react-markdown-unsanitized-raw-html": "error",
    "react-doctor/rendering-animate-svg-wrapper": "error",
    "react-doctor/rendering-conditional-render": "error",
    "react-doctor/rendering-hydration-mismatch-time": "error",
    "react-doctor/rendering-hydration-no-flicker": "error",
    "react-doctor/rendering-script-defer-async": "error",
    "react-doctor/rendering-svg-precision": "error",
    "react-doctor/rendering-usetransition-loading": "error",
    "react-doctor/rerender-defer-reads-hook": "error",
    "react-doctor/rerender-derived-state-from-hook": "error",
    "react-doctor/rerender-functional-setstate": "error",
    "react-doctor/rerender-lazy-ref-init": "error",
    "react-doctor/rerender-lazy-state-init": "error",
    "react-doctor/rerender-memo-before-early-return": "error",
    "react-doctor/rerender-state-only-in-handlers": "error",
    "react-doctor/rerender-transitions-scroll": "error",
    "react-doctor/role-button-requires-complete-keyboard-activation": "error",
    "react-doctor/server-after-nonblocking": "error",
    "react-doctor/server-auth-actions": "error",
    "react-doctor/server-cache-with-object-literal": "error",
    "react-doctor/server-dedup-props": "error",
    "react-doctor/server-hoist-static-io": "error",
    "react-doctor/server-no-mutable-module-state": "error",
    "react-doctor/server-sequential-independent-await": "error",
    "react-doctor/waapi-animation-in-render": "error",
    "react-doctor/web-animation-offsets-valid": "error",
    "react-doctor/webgl-no-sync-readback-in-animation-loop": "error",
    "react-doctor/window-open-without-noopener": "error",
    "react-doctor/zod-v4-no-deprecated-error-apis": "error",
    "react-doctor/zod-v4-no-deprecated-error-customization": "error",
    "react-doctor/zod-v4-no-deprecated-schema-apis": "error",
    "react-doctor/zod-v4-prefer-top-level-string-formats": "error",
    // react-doctor:end
  },
  overrides: [
    {
      // ビルド時に Node で直接実行するツール類（ブラウザには載らない）
      files: ["tools/**/*.ts"],
      rules: {
        "import/no-nodejs-modules": "off",
        "node/no-sync": "off",
      },
    },
    {
      // Storybook stories
      files: ["**/*.stories.*", "**/*.story.*"],
      rules: {
        "import/no-default-export": "off",
        "react/rules-of-hooks": "off",
        "typescript/consistent-type-assertions": "off",
        "typescript/no-explicit-any": "off",
        "typescript/no-unsafe-argument": "off",
        "typescript/no-unsafe-assignment": "off",

        // eslint-plugin-storybook (jsPlugin)
        "storybook/await-interactions": "error",
        "storybook/context-in-play-function": "error",
        "storybook/csf-component": "error",
        "storybook/default-exports": "error",
        "storybook/hierarchy-separator": "error",
        "storybook/meta-inline-properties": "error",
        "storybook/meta-satisfies-type": "error",
        "storybook/no-redundant-story-name": "error",
        "storybook/no-renderer-packages": "error",
        "storybook/no-stories-of": "error",
        "storybook/no-title-property-in-meta": "error",
        "storybook/prefer-pascal-case": "error",
        "storybook/story-exports": "error",
        "storybook/use-storybook-expect": "error",
        "storybook/use-storybook-testing-library": "error",

        // ── @tanstack/eslint-plugin-query (jsPlugin) ──
        "@tanstack/query/prefer-query-options": "off",
      },
      jsPlugins: ["eslint-plugin-storybook"],
    },
    {
      // Storybook main config
      files: [".storybook/main.*"],
      rules: {
        "storybook/no-uninstalled-addons": "error",
      },
      jsPlugins: ["eslint-plugin-storybook"],
    },
    {
      // Test files
      files: ["**/*.test.*", "**/*.spec.*", "**/*.test-d.*"],
      rules: {
        "eslint/init-declarations": "off",
        "eslint/no-empty-function": "off",
        "eslint/no-undef": "off",
        "typescript/consistent-type-assertions": "off",
        "typescript/no-explicit-any": "off",
        "typescript/no-unsafe-argument": "off",
        "typescript/no-unsafe-assignment": "off",
        "typescript/no-unsafe-type-assertion": "off",
      },
    },
    {
      // default export を許可するファイル群:
      files: [
        ".storybook/main.ts",
        ".storybook/preview.tsx",
        "next.config.ts",
        "oxfmt.config.ts",
        "oxlint.config.ts",
        "postcss.config.mjs",
        "vitest.config.ts",
        "vitest.globalSetup.ts",
        // Next.js 規約ファイル (vitest.config.ts と同じ brace glob スタイル)
        "src/**/{default,error,forbidden,global-error,global-not-found,layout,loading,not-found,page,template,unauthorized}.tsx",
        "src/**/{instrumentation-client,instrumentation,proxy,sitemap}.ts",
        "tools/oxlint-rules/**/*.ts",
      ],
      rules: {
        "import/no-default-export": "off",
      },
    },
  ],
});
