/**
 * This file is AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { HttpResponse, http } from "msw";
import { faker } from "@faker-js/faker/locale/ja";

faker.seed(1);

const baseURL = "https://jsonplaceholder.typicode.com";
const MAX_ARRAY_LENGTH = 20;

// Map to store counters for each API endpoint
const apiCounters = new Map<string, number>();

const next = (apiKey: string) => {
  let currentCount = apiCounters.get(apiKey) ?? 0;
  if (currentCount === Number.MAX_SAFE_INTEGER - 1) {
    currentCount = 0;
  }
  apiCounters.set(apiKey, currentCount + 1);
  return currentCount;
};

export const handlers = [
  http.get(`${baseURL}/posts`, async ({ request }) => {
    const shouldEchoRequestBody = false;
    let requestJson = null;
    if (shouldEchoRequestBody && ["post", "put", "patch"].includes("get")) {
      try {
        requestJson = await request.clone().json();
      } catch (e) {
        requestJson = null;
      }
    }

    const resultArray = [
      [await getListPosts200Response(), { status: 200 }],
    ] as [any, { status: number }][];

    const [body, init] = resultArray[next(`get /posts`) % resultArray.length];
    const responseJson =
      requestJson && body && typeof body === "object" && !Array.isArray(body)
        ? { ...body, ...requestJson }
        : body;
    return HttpResponse.json(responseJson, init);
  }),
  http.post(`${baseURL}/posts`, async ({ request }) => {
    const shouldEchoRequestBody = false;
    let requestJson = null;
    if (shouldEchoRequestBody && ["post", "put", "patch"].includes("post")) {
      try {
        requestJson = await request.clone().json();
      } catch (e) {
        requestJson = null;
      }
    }

    const resultArray = [
      [await getPostPosts201Response(), { status: 201 }],
    ] as [any, { status: number }][];

    const [body, init] = resultArray[next(`post /posts`) % resultArray.length];
    const responseJson =
      requestJson && body && typeof body === "object" && !Array.isArray(body)
        ? { ...body, ...requestJson }
        : body;
    return HttpResponse.json(responseJson, init);
  }),
  http.delete(`${baseURL}/posts/:postId`, async ({ request }) => {
    const shouldEchoRequestBody = false;
    let requestJson = null;
    if (shouldEchoRequestBody && ["post", "put", "patch"].includes("delete")) {
      try {
        requestJson = await request.clone().json();
      } catch (e) {
        requestJson = null;
      }
    }

    const resultArray = [[undefined, { status: 200 }]] as [
      any,
      { status: number },
    ][];

    const [body, init] =
      resultArray[next(`delete /posts/:postId`) % resultArray.length];
    const responseJson =
      requestJson && body && typeof body === "object" && !Array.isArray(body)
        ? { ...body, ...requestJson }
        : body;
    return HttpResponse.json(responseJson, init);
  }),
  http.get(`${baseURL}/posts/:postId`, async ({ request }) => {
    const shouldEchoRequestBody = false;
    let requestJson = null;
    if (shouldEchoRequestBody && ["post", "put", "patch"].includes("get")) {
      try {
        requestJson = await request.clone().json();
      } catch (e) {
        requestJson = null;
      }
    }

    const resultArray = [
      [await getGetPostsPostId200Response(), { status: 200 }],
    ] as [any, { status: number }][];

    const [body, init] =
      resultArray[next(`get /posts/:postId`) % resultArray.length];
    const responseJson =
      requestJson && body && typeof body === "object" && !Array.isArray(body)
        ? { ...body, ...requestJson }
        : body;
    return HttpResponse.json(responseJson, init);
  }),
  http.patch(`${baseURL}/posts/:postId`, async ({ request }) => {
    const shouldEchoRequestBody = false;
    let requestJson = null;
    if (shouldEchoRequestBody && ["post", "put", "patch"].includes("patch")) {
      try {
        requestJson = await request.clone().json();
      } catch (e) {
        requestJson = null;
      }
    }

    const resultArray = [
      [await getPatchPostsPostId200Response(), { status: 200 }],
    ] as [any, { status: number }][];

    const [body, init] =
      resultArray[next(`patch /posts/:postId`) % resultArray.length];
    const responseJson =
      requestJson && body && typeof body === "object" && !Array.isArray(body)
        ? { ...body, ...requestJson }
        : body;
    return HttpResponse.json(responseJson, init);
  }),
];

export function getListPosts200Response() {
  return (() => {
    const arrayMin = 1;
    const arrayMax = MAX_ARRAY_LENGTH;
    const safeMin = Math.min(arrayMin, arrayMax);
    return [
      ...new Array(faker.number.int({ min: safeMin, max: arrayMax })).keys(),
    ].map((_) => ({
      userId: faker.number.int(),
      id: faker.number.int(),
      title: faker.lorem.words(),
      body: faker.lorem.words(),
    }));
  })();
}

export function getPostPosts201Response() {
  return {
    userId: faker.number.int(),
    id: faker.number.int(),
    title: faker.lorem.words(),
    body: faker.lorem.words(),
  };
}

export function getGetPostsPostId200Response() {
  return {
    userId: faker.number.int(),
    id: faker.number.int(),
    title: faker.lorem.words(),
    body: faker.lorem.words(),
  };
}

export function getPatchPostsPostId200Response() {
  return {
    userId: faker.number.int(),
    id: faker.number.int(),
    title: faker.lorem.words(),
    body: faker.lorem.words(),
  };
}
