name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup environment
        run: cp .env.development .env.local

      - name: Type check
        run: pnpm check-types

      - name: Lint
        run: pnpm lint

      - name: Check unused dependencies
        run: pnpm knip

      - name: Test
        run: pnpm test:unit

      - name: Build
        run: pnpm build
