name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
          cache: 'yarn'

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Install dependencies
        run: yarn install --immutable

      - name: Type check
        run: yarn check-types

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
